# Generated by Django 4.2.3 on 2023-07-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=30)),
                ('facilities', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20)),
                ('renovation', models.CharField(choices=[('N', 'без отделки'), ('Y', 'с отделкой'), ('C', 'косметический'), ('R', 'евроремонт'), ('D', 'дизайнерский')], max_length=20)),
                ('price', models.IntegerField(default='Договорная')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('number_of_rooms', models.IntegerField()),
                ('floor_number', models.IntegerField()),
                ('living_area', models.FloatField()),
                ('kitchen', models.FloatField()),
                ('year_of_construction', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('square', models.FloatField()),
                ('address', models.CharField(max_length=30)),
                ('facilities', models.CharField(blank=True, max_length=100)),
                ('renovation', models.CharField(choices=[('N', 'без отделки'), ('Y', 'с отделкой'), ('C', 'косметический'), ('R', 'евроремонт'), ('D', 'дизайнерский')], max_length=20)),
                ('price', models.IntegerField(default='Договорная')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('quantity_parking_spaces', models.IntegerField()),
                ('heating', models.CharField(choices=[('Y', 'есть'), ('N', 'отсутствует')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('square', models.FloatField()),
                ('address', models.CharField(max_length=30)),
                ('facilities', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20)),
                ('renovation', models.CharField(choices=[('N', 'без отделки'), ('Y', 'с отделкой'), ('C', 'косметический'), ('R', 'евроремонт'), ('D', 'дизайнерский')], max_length=20)),
                ('price', models.IntegerField(default='Договорная')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('category', models.CharField(choices=[('H', 'дом'), ('C', 'коттедж'), ('M', 'усадьба')], max_length=20)),
                ('number_of_rooms', models.IntegerField()),
                ('number_of_floors', models.IntegerField()),
                ('living_area', models.FloatField()),
                ('year_of_construction', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Industrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('square', models.FloatField()),
                ('address', models.CharField(max_length=30)),
                ('facilities', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20)),
                ('renovation', models.CharField(choices=[('N', 'без отделки'), ('Y', 'с отделкой'), ('C', 'косметический'), ('R', 'евроремонт'), ('D', 'дизайнерский')], max_length=20)),
                ('price', models.IntegerField(default='Договорная')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('number_of_separate_premises', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('square', models.FloatField()),
                ('address', models.CharField(max_length=30)),
                ('facilities', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20)),
                ('renovation', models.CharField(choices=[('N', 'без отделки'), ('Y', 'с отделкой'), ('C', 'косметический'), ('R', 'евроремонт'), ('D', 'дизайнерский')], max_length=20)),
                ('price', models.IntegerField(default='Договорная')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('floor_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('square', models.FloatField()),
                ('address', models.CharField(max_length=30)),
                ('facilities', models.CharField(blank=True, max_length=100)),
                ('renovation', models.CharField(choices=[('N', 'без отделки'), ('Y', 'с отделкой'), ('C', 'косметический'), ('R', 'евроремонт'), ('D', 'дизайнерский')], max_length=20)),
                ('price', models.IntegerField(default='Договорная')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('quantity_parking_spaces', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('square', models.FloatField()),
                ('address', models.CharField(max_length=30)),
                ('facilities', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20)),
                ('renovation', models.CharField(choices=[('N', 'без отделки'), ('Y', 'с отделкой'), ('C', 'косметический'), ('R', 'евроремонт'), ('D', 'дизайнерский')], max_length=20)),
                ('price', models.IntegerField(default='Договорная')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('location', models.CharField(choices=[('S', 'отдельное здание'), ('M', 'в торговом центре')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('square', models.FloatField()),
                ('address', models.CharField(max_length=30)),
                ('facilities', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20)),
                ('renovation', models.CharField(choices=[('N', 'без отделки'), ('Y', 'с отделкой'), ('C', 'косметический'), ('R', 'евроремонт'), ('D', 'дизайнерский')], max_length=20)),
                ('price', models.IntegerField(default='Договорная')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('number_of_separate_premises', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
