# Generated by Django 4.2.3 on 2023-07-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='garage',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='office',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parking',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trade',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
