# Generated by Django 4.2.3 on 2023-07-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_flat_title_alter_garage_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garage',
            old_name='square',
            new_name='total_area',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='square',
            new_name='total_area',
        ),
        migrations.RenameField(
            model_name='industrial',
            old_name='square',
            new_name='total_area',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='square',
            new_name='total_area',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='square',
            new_name='total_area',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='square',
            new_name='total_area',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='square',
            new_name='total_area',
        ),
        migrations.AddField(
            model_name='flat',
            name='total_area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
