# Generated by Django 4.2.3 on 2023-07-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_rename_square_garage_total_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='flat',
            name='facilities',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='garage',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='garage',
            name='facilities',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='house',
            name='facilities',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='facilities',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='office',
            name='facilities',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='parking',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='parking',
            name='facilities',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='trade',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='trade',
            name='facilities',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='facilities',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
