# Generated by Django 4.2.3 on 2023-07-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_flat_creator_garage_creator_house_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='garage',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industrial',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parking',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
