# Generated by Django 4.2.3 on 2023-07-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_flat_is_moderated_garage_is_moderated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='house',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='industrial',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='office',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='photo',
        ),
        migrations.AddField(
            model_name='flat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='garage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='industrial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='office',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='parking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='trade',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
