# Generated by Django 4.2.3 on 2023-07-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_remove_flat_photo_remove_garage_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='renovation',
        ),
        migrations.AlterField(
            model_name='flat',
            name='condition',
            field=models.CharField(blank=True, choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='condition',
            field=models.CharField(blank=True, choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='condition',
            field=models.CharField(blank=True, choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='condition',
            field=models.CharField(blank=True, choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='condition',
            field=models.CharField(blank=True, choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20, null=True),
        ),
    ]
