# Generated by Django 4.2.3 on 2023-07-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_remove_warehouse_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='renovation',
        ),
        migrations.RemoveField(
            model_name='industrial',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='industrial',
            name='renovation',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='renovation',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='renovation',
        ),
    ]
