# Generated by Django 4.2.3 on 2023-08-03 00:19

import django.core.validators
from django.db import migrations, models
import sale.models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_remove_garage_renovation_remove_industrial_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='flat',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='flat',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='flat',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='garage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='garage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='garage',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='garage',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='house',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='house',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='house',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='house',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='industrial',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='industrial',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='industrial',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='industrial',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='office',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='office',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='office',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='office',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='parking',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='parking',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='parking',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='parking',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='trade',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='trade',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='trade',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='trade',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flat',
            name='condition',
            field=models.CharField(choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flat',
            name='description',
            field=models.CharField(max_length=4000, validators=[django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='facilities',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='kitchen',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='living_area',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='number_of_rooms',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='flat',
            name='year_of_construction',
            field=models.PositiveIntegerField(validators=[sale.models.validate_year_of_construction]),
        ),
        migrations.AlterField(
            model_name='garage',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='garage',
            name='description',
            field=models.CharField(max_length=4000, validators=[django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='garage',
            name='facilities',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='garage',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='garage',
            name='quantity_parking_spaces',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='condition',
            field=models.CharField(choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.CharField(max_length=4000, validators=[django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='facilities',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='house',
            name='living_area',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_of_floors',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_of_rooms',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='year_of_construction',
            field=models.PositiveIntegerField(validators=[sale.models.validate_year_of_construction]),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='description',
            field=models.CharField(max_length=4000, validators=[django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='facilities',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='number_of_separate_premises',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='office',
            name='condition',
            field=models.CharField(choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='office',
            name='description',
            field=models.CharField(max_length=4000, validators=[django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='office',
            name='facilities',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='office',
            name='floor_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='office',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parking',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parking',
            name='description',
            field=models.CharField(max_length=4000, validators=[django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='parking',
            name='facilities',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='parking',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parking',
            name='quantity_parking_spaces',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trade',
            name='condition',
            field=models.CharField(choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='description',
            field=models.CharField(max_length=4000, validators=[django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='facilities',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.CharField(max_length=4000, validators=[django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='facilities',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='number_of_separate_premises',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
