# Generated by Django 4.2.3 on 2023-08-05 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0012_house_bathroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrial',
            name='condition',
            field=models.CharField(blank=True, choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20),
        ),
        migrations.AddField(
            model_name='office',
            name='number_of_floors',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='number_of_separate_premises',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='renovation',
            field=models.CharField(choices=[('N', 'без отделки'), ('Y', 'с отделкой'), ('C', 'косметический'), ('R', 'евроремонт'), ('D', 'дизайнерский')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='condition',
            field=models.CharField(blank=True, choices=[('N', 'новостройка'), ('S', 'вторичка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='garage',
            name='heating',
            field=models.CharField(blank=True, choices=[('Gas', 'Газовое'), ('Central', 'Центральное'), ('Electric', 'Электрическое'), ('Stove', 'Печное'), ('No', 'Отсутствует')], max_length=20),
        ),
        migrations.AlterField(
            model_name='garage',
            name='quantity_parking_spaces',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='location',
            field=models.CharField(choices=[('S', 'Отдельное здание'), ('M', 'В другом здании')], max_length=20),
        ),
    ]
